apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nqueens
spec:
  entrypoint: nqueens-job
  templates:
  - name: nqueens-job
    steps:
    - - name: nqueens-genetic-job
        template: nqueens-genetic-job
    # - - name: delete-job
    #     template: delete-job
    #     arguments:
    #       parameters:
    #       - name: job-name
    #         value: '{{steps.nqueens-genetic-job.outputs.parameters.job-name}}'
  - name: nqueens-genetic-job
    resource:
      action: create
      successCondition: status.succeeded > 1
      failureCondition: status.failed > 0
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          namespace: default
          name: nqueens-5
          labels:
            job: n-queens
        spec:
          parallelism: 5
          completions: 5
          template: 
            metadata:
              labels:
                job: n-queens
            spec:
              containers:
              - name: worker
                image: soldierzsebbi/nqueens:latest
                env:
                - name: BOARD_SIZE
                  value: "21"
                - name: POPULATION_SIZE
                  value: "10"
                - name: GENERATION_SIZE
                  value: "-1"
              restartPolicy: Never
    outputs:
      parameters:
      - name: job-name
        valueFrom:
          jsonPath: '{.metadata.name}'
      - name: job-uid
        valueFrom:
          jsonPath: '{.metadata.uid}'

  # - name: delete-job
  #   inputs:
  #     parameters:
  #     - name: job-name
  #   resource:
  #     action: delete
  #     manifest: |
  #       apiVersion: batch/v1
  #       kind: Job
  #       metadata:
  #         name: {{inputs.parameters.job-name}}