apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thab
  namespace: default
  uid: 4178cf18-842d-49c2-ab69-c92ec00a3b01
  resourceVersion: '110116'
  creationTimestamp: '2024-02-02T13:06:50Z'
  labels:
    k8slens-edit-resource-version: v1
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/default/roles/thab
rules:
  - verbs:
      - get
      - watch
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - jobs
  - verbs:
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
      - get
      - delete
    apiGroups:
      - batch
    resources:
      - jobs